import { NextRequest, NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase-admin';
import { generateContentWithRetry } from '@/lib/gemini';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { clientId, message, history } = body;

    if (!clientId || !message) {
      return NextResponse.json({ error: 'Missing clientId or message parameter' }, { status: 400 });
    }

    // 1. Fetch Client Details
    const clientDoc = await adminDb.collection('clients').doc(clientId).get();
    if (!clientDoc.exists) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }
    const clientData = clientDoc.data()!;

    // 2. Fetch Latest Audit Run
    const latestAuditSnapshot = await adminDb.collection('audit_runs')
      .where('clientId', '==', clientId)
      .orderBy('createdAt', 'desc')
      .limit(1)
      .get();

    if (latestAuditSnapshot.empty) {
      return NextResponse.json({ error: 'No audits found for this client. Please run an audit first.' }, { status: 400 });
    }

    const currentAudit = latestAuditSnapshot.docs[0].data();

    // 3. Fetch Historical Runs
    const historySnapshot = await adminDb.collection('audit_runs')
      .where('clientId', '==', clientId)
      .orderBy('createdAt', 'desc')
      .limit(6)
      .get();

    const historicalAudits = historySnapshot.docs
      .map(doc => ({
        id: doc.id,
        score: doc.data().score,
        grade: doc.data().grade,
        createdAt: doc.data().createdAt.toDate()
      }))
      .filter(doc => doc.id !== latestAuditSnapshot.docs[0].id);

    // 4. Construct System Instructions
    const systemInstruction = `
    You are the "Tracking Health AI" chatbot investigator. Your job is to help users understand their Google Analytics 4 (GA4) and Google Tag Manager (GTM) implementations, based ONLY on the audit results and history generated by the application.
    You do NOT have direct access to live GA4 or GTM APIs. You must rely entirely on the provided audit run data and historical context to answer the user's questions.

    Here is the context of the client you are investigating:
    - Client Name: ${clientData.name}
    - Industry: ${clientData.industry}

    Current Audit Run Data:
    - Health Score: ${currentAudit.score}/100 (Grade: ${currentAudit.grade})
    - Issues Detected (Failed Audits):
    ${JSON.stringify(currentAudit.issues, null, 2)}
    - All Audit Rules Checked:
    ${JSON.stringify(currentAudit.results.map((r: any) => ({ title: r.title, category: r.category, passed: r.passed, severity: r.severity })), null, 2)}

    Historical Audits:
    ${JSON.stringify(historicalAudits, null, 2)}

    Instructions:
    1. Answer the user's questions based on the audit results.
    2. Be professional, clear, agency-ready, and technical when necessary, but explain concepts in simple terms.
    3. Suggest which issues to fix first (prioritizing 'critical' and 'high' severity).
    4. If asked about GA4 or GTM configurations, reference the actual issues in the audit results.
    5. If the user asks about something unrelated, politely steer them back to their analytics and tag tracking audit.
    `;

    // Format chat history to match Gemini SDK expected format
    const chatHistory = (history || []).map((msg: any) => ({
      role: msg.role === 'user' ? 'user' : 'model',
      parts: [{ text: msg.content }]
    }));

    // 5. Send message using Gemini with retry/fallback
    const responseText = await generateContentWithRetry(message, {
      systemInstruction: systemInstruction,
      chatHistory: chatHistory,
    });

    return NextResponse.json({ response: responseText });
  } catch (error) {
    console.error('Error in AI chat investigation:', error);
    return NextResponse.json({ error: (error as Error).message }, { status: 500 });
  }
}
